version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: bolt-ai-development
    image: bolt-ai:development
    command: ["pnpm","run","dev","--","--host","0.0.0.0","--port","5173"]
    environment:
      NODE_ENV: "development"
      HOST: "0.0.0.0"
      PORT: "5173"
      RUNNING_IN_DOCKER: "true"
      VITE_LOG_LEVEL: "${VITE_LOG_LEVEL:-debug}"

      # HMR via HTTPS por trás do Traefik
      VITE_HMR_PROTOCOL: "wss"
      VITE_HMR_HOST: "bolt.ianeuralinker.com"
      VITE_HMR_PORT: "443"

      # chaves (se exigidas já em dev)
      GROQ_API_KEY: "${GROQ_API_KEY}"
      HuggingFace_API_KEY: "${HuggingFace_API_KEY}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
      OPEN_ROUTER_API_KEY: "${OPEN_ROUTER_API_KEY}"
      GOOGLE_GENERATIVE_AI_API_KEY: "${GOOGLE_GENERATIVE_AI_API_KEY}"
      OLLAMA_API_BASE_URL: "${OLLAMA_API_BASE_URL}"
      XAI_API_KEY: "${XAI_API_KEY}"
      TOGETHER_API_KEY: "${TOGETHER_API_KEY}"
      TOGETHER_API_BASE_URL: "${TOGETHER_API_BASE_URL}"
      AWS_BEDROCK_CONFIG: "${AWS_BEDROCK_CONFIG}"

    # publicar a porta ajuda nos testes locais; Traefik não exige
    ports:
      - "5173:5173"

    # healthcheck para o Traefik só rotear quando o app responder
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:5173/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped
